# permissions for end users to view buyers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buyer-viewer-role
rules:
- apiGroups:
  - myapp.spike.com
  resources:
  - buyers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - myapp.spike.com
  resources:
  - buyers/status
  verbs:
  - get
