# permissions for end users to edit sellers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seller-editor-role
rules:
- apiGroups:
  - myapp.spike.com
  resources:
  - sellers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myapp.spike.com
  resources:
  - sellers/status
  verbs:
  - get
