# permissions for end users to edit spikeorders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spikeorder-editor-role
rules:
- apiGroups:
  - myapp.spike.com
  resources:
  - spikeorders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myapp.spike.com
  resources:
  - spikeorders/status
  verbs:
  - get
