# permissions for end users to view spikeorders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spikeorder-viewer-role
rules:
- apiGroups:
  - myapp.spike.com
  resources:
  - spikeorders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - myapp.spike.com
  resources:
  - spikeorders/status
  verbs:
  - get
